### ISSUE TITLE
P2P installer

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/installer#3]
Quoting from a readme:

> It is nice to configure one brick but maybe you could discover that the installer could move the JDK one manual process to another brick and hte installer it is possible to replicate to another remote brick. Play with the help to discover the way.

Well, it might be possible to connect to a different brick via Bluetooth PAN. You could then compress the installed JDK, transfer it over SCP/SSH to the second brick and then unpack it there. IDK about how to fully automate it.

**Comment by jabrena** [comment]
Little by litte, but it is interesting @JakubVanek

**Comment by JakubVanek** [comment]
Well, it was written in README. It should be tracked as a feature request.

**Comment by jabrena** [comment]
I saw it. Give me few days to test everything because now the installer offer the support for Java 10, but I need to offer a Stretch support. I will review the backlog for v0.8.0 to limit the scope for:

+ Support Java 10
+ Support for Debian Stretch for EV3

In v0.9.0 I will continue with the rest of the issue.
With more hands is easier to evolve any Open Source project. 

Good energy @JakubVanek !!!

Cheers

**Comment by jabrena** [comment]
Well, we added the bluetooth fature in the main backlog:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues

We will follow this issue from there
